import RNFetchBlob from 'rn-fetch-blob';
import { Platform } from 'react-native';

/**
 * Customer Config
 * - access_token: Customer Access Token is generated by ARMS Backend and to indicate customer.
 * - api_url: Customer API URL, please take note on http:// or https:// for url.
 * - app_display_name: Customer App Display Name.
 * - sender_id: Customer App Push Notification Firebase Sender ID in Firebase Portal (For Android Only).
 * - company_name: Customer Company Name.
 * - company_logo_url: Customer logo url in ARMS Backend.
 * - company_logo_local: Customer logo path in local device document folder.
 * - app_theme: Customer default app theme color.
 * 
 * Access Token Desc
 * - maximus2019  : ARMS DEV
 * - luke2019     : ARMS Luke QC
 * - mbm2019      : ARMS Mobile Membership
 * - 2019fasons5  : 5Ringgit Mobile Membership
 * - mffa2019jh   : MFFA
 * - fif50ssalo   : 50percent Hair Salon
 * - cent2019mx   : Centro Maxx Membership
 * - 1911pkthq9   : PKT Wholesale Warehouse
 * - 2020smo.12   : SYARIKAT MUDA OSMAN SDN BHD
 * - dm2021eoam     : ARMS Demo Mobile Membership
 * 
 */

var access_token = 'luke2019'; // Set Customer Access Token Here.
var api_url, app_display_name, sender_id, company_name, company_logo_url, company_logo_local, app_theme = "";
const folder_path_prefix = (Platform.OS=="android") ? "file://" : "";
switch(access_token){
  /**
   * ARMS Luke QC
   */
  case 'luke2019':
    api_url = 'https://luke.arms.com.my';
    app_display_name = 'ARMS Membership Luke';
    sender_id = '461117249956';
    company_name = 'ARMS SOFTWARE INTERNATION S/B';
    company_logo_url = 'ui/logo.png';
    company_logo_local = `${folder_path_prefix}${RNFetchBlob.fs.dirs.DocumentDir}/logo/logo.png`;
    app_theme = 'default_theme';
    break;

  /**
   * ARMS Mbmember
   */
  case 'mbm2019':
    api_url = 'https://mbmember.arms.com.my';
    app_display_name = 'ARMS Mobile Membership';
    sender_id = '461117249956';
    company_name = 'ARMS SOFTWARE INTERNATION S/B';
    company_logo_url = 'ui/logo.png';
    company_logo_local = `${folder_path_prefix}${RNFetchBlob.fs.dirs.DocumentDir}/logo/logo.png`;
    app_theme = 'default_theme';
    break;
  
  /**
   * 5 Ringgit
   */
  case '2019fasons5':
    api_url = 'https://5ringgit.arms-go.com';
    app_display_name = '5Ringgit Mobile Membership';
    sender_id = '799208789625';
    company_name = 'Fasons Five Sdn Bhd';
    company_logo_url = 'ui/logo.png';
    company_logo_local = `${folder_path_prefix}${RNFetchBlob.fs.dirs.DocumentDir}/logo/logo.png`;
    app_theme = 'default_theme';
    break;
  
  /**
   * MFFA
   */
  case 'mffa2019jh':
    api_url = 'https://mffa.arms-go.com';
    app_display_name = 'MFFA';
    sender_id = '434340184262';
    company_name = 'MY FISHING FENZY ACADEMY';
    company_logo_url = 'ui/logo.png';
    company_logo_local = `${folder_path_prefix}${RNFetchBlob.fs.dirs.DocumentDir}/logo/logo.png`;
    app_theme = 'theme_4';
    break;
  
  /**
   * 50percent Hair Salon
   */
  case 'fif50ssalo':
    api_url = 'https://50percentsalon.arms-go.com';
    app_display_name = '50percent Hair Salon';
    sender_id = '523387962996';
    company_name = 'Fifty Percent Group Sdn Bhd';
    company_logo_url = 'ui/logo.png';
    company_logo_local = `${folder_path_prefix}${RNFetchBlob.fs.dirs.DocumentDir}/logo/logo.png`;
    app_theme = 'theme_1';
    break;

  /**
   * Centro Maxx Membership
   */
  case 'cent2019mx':
    api_url = 'https://centromaxx.arms-go.com';
    app_display_name = 'Centro Maxx';
    sender_id = '800960161277';
    company_name = 'Centro Maxx Sdn Bhd';
    company_logo_url = 'ui/logo.png';
    company_logo_local = `${folder_path_prefix}${RNFetchBlob.fs.dirs.DocumentDir}/logo/logo.png`;
    app_theme = 'theme_4';
    break;

  /**
   * PKT Wholesale Warehouse
   */
  case '1911pkthq9':
    api_url = 'https://12shoppkt.arms.com.my';
    app_display_name = 'PKT';
    sender_id = '163091751952';
    company_name = 'PKT Wholesale Warehouse Sdn Bhd';
    company_logo_url = 'ui/logo.png';
    company_logo_local = `${folder_path_prefix}${RNFetchBlob.fs.dirs.DocumentDir}/logo/logo.png`;
    app_theme = 'theme_6';
    break;
  
  /**
   * SYARIKAT MUDA OSMAN SDN BHD
   */
  case '2020smo.12':
    api_url = 'https://smohq.arms.com.my';
    app_display_name = 'KLIK SMO';
    sender_id = '89038034656';
    company_name = 'SYARIKAT MUDA OSMAN SDN BHD';
    company_logo_url = 'ui/logo.png';
    company_logo_local = `${folder_path_prefix}${RNFetchBlob.fs.dirs.DocumentDir}/logo/logo.png`;
    app_theme = 'default_theme';
    break;

  /**
   * ARMS Demo Server
   */
  case 'dm2021eoam':
    api_url = 'https://demo.arms.com.my';
    app_display_name = 'ARMS Demo Mobile Membership';
    sender_id = '461117249956';
    company_name = 'ARMS SOFTWARE INTERNATIONAL S/B';
    company_logo_url = 'ui/logo.png';
    company_logo_local = `${folder_path_prefix}${RNFetchBlob.fs.dirs.DocumentDir}/logo/logo.png`;
    app_theme = 'default_theme';
    break;
  
  /**
   * Maximus (DEV Server)  
   */  
  default:
    api_url = 'http://maximus.ddns.my:2001';
    app_display_name = 'ARMS Membership App';
    sender_id = '461117249956';
    company_name = 'ARMS SOFTWARE INTERNATION S/B';
    company_logo_url = 'ui/logo.png';
    company_logo_local = `${folder_path_prefix}${RNFetchBlob.fs.dirs.DocumentDir}/logo/logo.png`;
    app_theme = 'default_theme';
    break;
}

export default {
  access_token, 
  api_url,
  app_display_name,
  sender_id,
  company_name,
  company_logo_url,
  company_logo_local,
  app_theme,
}