const images = {
  /**
   * Company Customize Config
   */
  company_logo: require("../Assets/Logo/logo.png"),
  loginLandingBackground: require('../Assets/Dummy/wallpaper.jpg'),

  /**
   * Icons Config
   */
  http: require("../Assets/Images/http.png"),
  lock: require("../Assets/Images/lock.png"),
  vpnKey: require("../Assets/Images/vpn_key.png"),
  face: require("../Assets/Images/face.png"),
  fingerPrint: require("../Assets/Images/finger_print.png"),
  passcodeLock: require("../Assets/Images/passcode.png"),
  arrowRight: require("../Assets/Images/arrow_right.png"),
  arrowLeft: require("../Assets/Images/arrow_left.png"),
  dropdown: require("../Assets/Images/dropdown.png"),
  dropup: require("../Assets/Images/dropup.png"),
  setting: require("../Assets/Images/settings.png"),
  localOffer: require("../Assets/Images/local_offer.png"),
  stockTakeSearch: require("../Assets/Images/stock_take.png"),
  search: require("../Assets/Images/search.png"),
  addCircle: require("../Assets/Images/add_circle.png"),
  assignment: require("../Assets/Images/assignment.png"),
  scanner: require("../Assets/Images/scanner.png"),
  deleteTrash: require("../Assets/Images/delete_trash.png"),
  imageNoAvailable: require("../Assets/Images/no_image_available.jpg"),
  info: require("../Assets/Images/info.png"),
  sync: require("../Assets/Images/sync.png"),
  server_settings: require("../Assets/Images/server_settings.png"),
  cloud_upload: require("../Assets/Images/cloud_upload.png"),
  check_box_blank: require("../Assets/Images/check_box_blank.png"),
  check_box_checked: require("../Assets/Images/check_box_checked.png"),
  add_square: require("../Assets/Images/add_square.png"),
  remove_square: require("../Assets/Images/remove_square.png"),
  barcode: require("../Assets/Images/barcode.png"),
  find_replace: require("../Assets/Images/find_replace.png"),
  qrcode: require("../Assets/Images/qr_code.png"),
  armsQRcode: require('../Assets/Images/armsQRcode.jpeg'),
  menu: require("../Assets/Images/menu.png"),
  drawer_back_img: require("../Assets/Images/drawer_back_img.png"),
  person: require("../Assets/Images/person.png"),
  voucher: require("../Assets/Images/voucher.png"),
  voucherInactive: require("../Assets/Images/voucher_inactive.png"),
  promo: require('../Assets/Images/promo.png'),
  voucherIcon: require('../Assets/Images/voucherIcon.png'),
  couponIcon: require("../Assets/Images/couponIcon.png"),
  home: require('../Assets/Images/home.png'),
  dashboard: require('../Assets/Images/dashboard.png'),
  history: require('../Assets/Images/history.png'),
  armsLogo: require('../Assets/Images/armslogo.png'),
  round_cancel: require('../Assets/Images/round_cancel.png'),
  round_tick: require('../Assets/Images/round_tick.png'),
  eBrochure: require('../Assets/Images/e_brochure.png'),
  phone: require("../Assets/Images/phone.png"),
  email: require("../Assets/Images/email.png"),
  card_membership: require("../Assets/Images/card_membership.png"),
  calendar: require("../Assets/Images/calendar.png"),
  location: require("../Assets/Images/location.png"),
  refresh: require("../Assets/Images/refresh.png"),
  store: require("../Assets/Images/store.png"),
  black_dot: require("../Assets/Images/black_dot.png"),
  shock: require("../Assets/Images/empty-pocket.png"),
  user: require("../Assets/Images/user.png"),
  edit: require("../Assets/Images/edit.png"),
  two_people: require("../Assets/Images/two_people.png"),
  shopping_cart: require("../Assets/Images/shopping_cart.png"),

  // Temporary Dummy Image
  // dummyB1: require('../Assets/Dummy/b1.jpg'),
  // dummyB2: require('../Assets/Dummy/b2.jpg'),
  // dummyB3: require('../Assets/Dummy/b3.jpg'),
  // dummyB4: require('../Assets/Dummy/b4.jpg'),
  // dummyB5: require('../Assets/Dummy/b5.jpg'),
  // dummyPromo1: require('../Assets/Dummy/hari-raya.jpg'),
  // dummyPromo2: require('../Assets/Dummy/chinese-newyear.jpg'),
  // dummyPromo3: require('../Assets/Dummy/deepavali.jpg'),
  // dummyPromo4: require('../Assets/Dummy/christmas.jpg'),
  // dummyPromo5: require('../Assets/Dummy/thaipusam.jpg'),
  // dummyPromo6: require('../Assets/Dummy/mooncake.jpg'),
  // dummyProd1: require('../Assets/Dummy/v1.jpg'),
  // dummyProd2: require('../Assets/Dummy/v2.jpg'),
  // dummyProd3: require('../Assets/Dummy/v3.jpg'),
  // dummyProd4: require('../Assets/Dummy/v4.jpg'),
  // dummyProd5: require('../Assets/Dummy/v5.jpg'),
  armsHQ: require('../Assets/Dummy/arms_hq.png'),
};

export default images;
